services:
  hms_db:
    image: mongo
    container_name: hms_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}

  mongo-express:
    image: mongo-express:latest
    container_name: hms_me
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
      - ME_CONFIG_MONGODB_SERVER=hsm_db
    depends_on:
      - hms_db

volumes:
  mongodb_data:
